
[packages]
    tobuild = [
        'tarantool-operator',
        'chat-operator',
        'presence-operator',
        'notifylocal-operator',
        'userlog-operator',
        'reporting-operator',
        'databucketer-operator',
    ]
